[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://maestro-front-anthony.netlify.app"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
