[[redirects]]
  from = "/api/*"
  to = "https://maestro-back-9st7.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://maestro-front-anthony.netlify.app"
    Access-Control-Allow-Credentials = "true"

